spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:soon;MODE=MYSQL;